# Generated by Django 4.2.6 on 2023-10-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domain_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('domain_name', models.CharField(max_length=100, unique=True)),
                ('domain_info', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='SearchLog',
        ),
    ]
