# Generated by Django 4.2.6 on 2023-10-07 20:10

from django.db import migrations, models
import django.db.models.deletion
import first_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_domain_delete_searchlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(validators=[first_app.models.validate_duration])),
                ('approval', models.CharField(choices=[('in progress', 'In Progress'), ('not started', 'Not Started'), ('completed', 'Completed')], default='not started', max_length=20)),
                ('license', models.CharField(max_length=256)),
                ('repository_link', models.URLField()),
                ('demo_link', models.URLField()),
                ('dataset_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('skill_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='ProjectSkillsReq',
            fields=[
                ('row_no', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('weightage', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.project')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.skills')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDomain',
            fields=[
                ('row_no', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.domain')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.user'),
        ),
        migrations.CreateModel(
            name='PersonsProject',
            fields=[
                ('row_no', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('approval', models.CharField(choices=[('selected', 'Selected'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='PersonSkills',
            fields=[
                ('row_no', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.user')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.skills')),
            ],
        ),
    ]
