# Generated by Django 4.2.6 on 2023-10-07 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_project_skills_user_alter_domain_domain_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectdomain',
            unique_together={('project', 'domain')},
        ),
    ]
