# Generated by Django 4.2.6 on 2023-10-07 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_alter_projectdomain_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personskills',
            unique_together={('person', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='projectskillsreq',
            unique_together={('project', 'skill', 'weightage')},
        ),
    ]
